services:
  front:
    image: front
    ports:
      - 5000:5000
  back:
    image: back
    ports:
      - 8000:8000
    volumes:
      - ./logs.txt:/app/logs.txt
    environment:
      REDIS: redis
  redis:
    image: redis